<?php
// $Id: xoops_version.php,v 1.2 2011/12/29 20:06:57 ohwada Exp $

// 2006-07-02 K.OHWADA
// change _MI_RSSHEADLINE_HEADLINES_xx to _MI_RSSHEADLINE_MD_RSSHEADLINE__xx
// change xoopsheadline to rssheadline

//=========================================================
// RSSC HeadLine
// based on xoopsHeadline
// 2006-07-02 K.OHWADA
//=========================================================
// based on xoopsHeadline
// Id: xoops_version.php,v 1.2 2005/03/18 12:52:49 onokazu Exp
//=========================================================

$moduleDirName      = basename(__DIR__);
$moduleDirNameUpper = mb_strtoupper($moduleDirName);

$modversion['name']        = _MI_RSSHEADLINE_NAME;
$modversion['version']     = 2.01;
$modversion['description'] = _MI_RSSHEADLINE_DESC;
$modversion['author']      = 'K.OHWADA<br>( https://linux.ohwada.jp/ )';
$modversion['credits']     = '';
$modversion['license']     = 'GPL see LICENSE';
$modversion['official']    = 0;
$modversion['image']       = 'assets/images/logoModule.png';
$modversion['dirname']     = $moduleDirName;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'rssheadline';

// ------------------- Mysql ------------------- //
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
//$modversion['tables'] = [
//    $moduleDirName . '_' . 'headline',
//];
$modversion['tables'] = [
    'rssheadline',
];


// ------------------- Help files ------------------- //
$modversion['help']        = 'page=help';
$modversion['helpsection'] = [
    ['name' => _MI_RSSHEADLINE_OVERVIEW, 'link' => 'page=help'],
    ['name' => _MI_RSSHEADLINE_DISCLAIMER, 'link' => 'page=disclaimer'],
    ['name' => _MI_RSSHEADLINE_LICENSE, 'link' => 'page=license'],
    ['name' => _MI_RSSHEADLINE_SUPPORT, 'link' => 'page=support'],
];

// Admin things
$modversion['system_menu']   = 1;
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file']        = 'headline.php';
$modversion['blocks'][1]['name']        = _MI_RSSHEADLINE_BNAME;
$modversion['blocks'][1]['description'] = 'Shows headline news via RDF/RSS news feed';
$modversion['blocks'][1]['show_func']   = 'b_rssheadline_show';
$modversion['blocks'][1]['template']    = 'rssheadline_block_rss.html';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file']        = 'rssheadline_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file']        = 'rssheadline_feed.html';
$modversion['templates'][2]['description'] = '';
