<?php
// $Id: xoops_version.php,v 1.2 2011/12/29 20:06:57 ohwada Exp $

// 2006-07-02 K.OHWADA
// change _MI_HEADLINES_xx to _MI_RSSC_HEADLINE_xx
// change xoopsheadline to rssc_headline

//=========================================================
// RSSC HeadLine
// based on xoopsHeadline
// 2006-07-02 K.OHWADA
//=========================================================
// based on xoopsHeadline
// Id: xoops_version.php,v 1.2 2005/03/18 12:52:49 onokazu Exp
//=========================================================

$modversion['name'] = _MI_RSSC_HEADLINE_NAME;
$modversion['version'] = 1.21;
$modversion['description'] = _MI_RSSC_HEADLINE_DESC;
$modversion['author'] = "K.OHWADA<br>( http://linux.ohwada.jp/ )";
$modversion['credits'] = "";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/rssc_headline_slogo.png";
$modversion['dirname'] = "rssc_headline";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "rssc_headline";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "headline.php";
$modversion['blocks'][1]['name'] = _MI_RSSC_HEADLINE_BNAME;
$modversion['blocks'][1]['description'] = "Shows headline news via RDF/RSS news feed";
$modversion['blocks'][1]['show_func'] = 'b_rssc_headline_show';
$modversion['blocks'][1]['template'] = 'rssc_headline_block_rss.html';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'rssc_headline_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'rssc_headline_feed.html';
$modversion['templates'][2]['description'] = '';
?>